### ISSUE TITLE
Определить лицензию

### ISSUE THREAD

**Issue by ForNeVeR** [sidristij/dotnetbook#14]
Добрый день. Я бы хотел немного поконтрибьютить в этот проект, но на данный момент меня останавливает отсутствие лицензии. Мне хотелось бы, чтобы мои изменения обладали внятным легальным статусом.

Можете, пожалуйста, определить лицензию на текст?

**Comment by mumusan** [comment]
Да, пока не занимался этим. Хотел бы чтобы лицензия созраняла авторство всех, кто внес вклад, но не мешала бы распространению. Можно подумать вместе :)

**Comment by ForNeVeR** [comment]
Ну, обычно для подобного рода проектов выбирают что-нибудь из разряда https://creativecommons.org/licenses/by/4.0/

Можно почитать подробнее тут: http://creativecommons.ru/licenses

Мне кажется, что лицензия cc-by (Attribution) лучше всего подойдёт для данного материала: другие люди смогут распространять и модифицировать текст, но будут обязаны указывать авторство (ну а самым простым способом сделать это будет просто дать ссылку на гитхаб — тут все контрибьюторы видны).

**Comment by mumusan** [comment]
Надо как-то защититься от печати книги. Могут отправить в издательство, а всех авторов мелким шрифтом - после оглавления

**Comment by ForNeVeR** [comment]
В таком случае можно затребовать non-commercial. Печатать будет можно, но нельзя будет извлекать из этого выгоду.

Впрочем, в таком случае будут сложности, если вы сами захотите издать платную книгу — придётся собирать разрешения от всех контрибьюторов. Если у вас такое (потенциальное) желание есть, то нужно по-хорошему организовывать какой-то [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement), заставлять всех соавторов с ним соглашаться, а там прописывать, что вы будете являться единоличным правообладателем на коммерческое издание. __(Да, это сложная и мутная схема, а я не юрист и толком тут уже ничего посоветовать не смогу.)__
