### ISSUE TITLE
Конвенция именования статей и содержания

### ISSUE THREAD

**Issue by GeorgeAlexandria** [sidristij/dotnetbook#22]
Предлагаю придерживаться того, что содержание и название заголовков и подзаголовков статей совпадают:

***Содержание***
- Работа CLR
  - Память
    - Стек
----------
***Название статьи: вариант \# 1***
# Работа CLR
### Стек
-------------
***Название статьи: вариант \# 2***
# Работа CLR. Память. Стек
-----------
Отображать можно по-разному, лишь бы было совпадение иерархии и названия в том или в ином виде.

**Comment by mumusan** [comment]
С этим абсолютно согласен. Просто с самого начала накидал некий план, а потом уже начал разработку.
