### ISSUE TITLE
Типичные ошибки реализации

### ISSUE THREAD

**Issue by sidristij** [sidristij/dotnetbook#37]

**Comment by AlexandrTsvetkov** [comment]
> Эта ошибка в топе ошибок .NET Framework касательно IDisposable: SuppressFinalize для класса, где нет финализатора. Встречается очень часто.

Разве это ошибка? Ведь от этого класса можно отнаследоваться, и там определить финализатор. Если метод `SuppressFinalize(this)` не будет вызван в методе `Dispose()` базового класса, тогда и он не будет вызван в классах наследниках. Я бы сказал так, что для `sealed` классов действует такое правило, которые вы описали.
