### ISSUE TITLE
Глава Исключения

### ISSUE THREAD

**Issue by sidristij** [sidristij/dotnetbook#51]
Здесь я предлагаю вести обсуждение главы Исключения. Ошибки, дополнения.

**Comment by ramonesz297** [comment]
У меня скорее уточнения, по поводу примера: https://github.com/sidristij/dotnetbook/blame/master/ExceptionalFlow/2-Exceptions-Architecture.md#L334.
Как я понял скорее всего имелось ввиду что-то вроде этого?
```csharp
public abstract class LoggerExceptionBase: Exception
{
    protected LoggerException(..);
}
public class IOLoggerException : LoggerExceptionBase
{
    internal IOLoggerException(..);
}
public class ConfigLoggerException : LoggerExceptionBase
{
    internal ConfigLoggerException(..);
}
```
Или же я попросту что-то упустил?

**Comment by sidristij** [comment]
Да, прошу прощения за опечатку!

**Comment by Guddiny** [comment]
> Этот пример кажется немного странным: и это не просто так. Для того чтобы показать исключительность проблем, возникающих в данном коде я сделал его несколько утрированным. Для начала посмотрим на метод **Parse**. Почему он должен выбрасывать исключение?

>Он принимает в качестве параметра строку, а в качестве результата - некоторое число, которое является значимым типом. По этому числу мы никак не можем определить, является ли оно результатом корректных вычислений или же нет: оно просто есть. Другими словами, в интерфейсе метода отсутствует возможность сообщить о проблеме;

Тут наверное имеется в виду метод **TryParse** ?
