### ISSUE TITLE
Глава Memory<T> и Span<T>

### ISSUE THREAD

**Issue by sidristij** [sidristij/dotnetbook#55]
Здесь я предлагаю вести обсуждение главы. Ошибки, дополнения.

**Comment by sidristij** [comment]
Здесь я предлагаю вести обсуждение главы. Ошибки, дополнения.

**Comment by vova-lantsov-dev** [comment]
@sidristij ```c#
var writeableInput = Unsafe.As<ReadOnlyMemory<char>, Memory<char>>(ref readOnlyInput);
```
Вопрос: а со спанами такое пройдёт?

**Comment by sidristij** [comment]
Нет, так не сработает ) Span/ReadOnlySpan - ref структуры, их нельзя использовать как параметры типа

**Comment by vlasovsv** [comment]
Нашёл, как мне видится, опечатку в коде главы:

> Как мы видим, Span<T> вводит абстракцию доступа к некоторому участку памяти, как на чтение, так и на запись. Что нам это дает? Если вспомнить, на основе чего еще может быть сделан Span, то мы вспомним как про неуправляемые ресурсы, так и про строки:

Далее следует пример:

```csharp
// Managed array
var array = new[] { '1', '2', '3', '4', '5', '6' };
var arrSpan = new Span<char>(array, 1, 3);
if (TryParseInt32(arrSpan, out var res1))
{
    Console.WriteLine(res1);
}

// String
var srcString = "123456";
var strSpan = srcString.AsSpan();
if (TryParseInt32(arrSpan, out var res2))
{
    Console.WriteLine(res2);
}

// void *
Span<char> buf = stackalloc char[6];
buf[0] = '1'; buf[1] = '2'; buf[2] = '3';
buf[3] = '4'; buf[4] = '5'; buf[5] = '6';

if (TryParseInt32(arrSpan, out var res3))
{
    Console.WriteLine(res3);
}

-----
234
234
234
```

В примерах для String и void* используется **arrSpan**, хотя по логике должен быть **strSpan** и **buf** соответственно.

Если я не прав, то извините за потраченное время.
