### ISSUE TITLE
Reference Types vs Value Types

### ISSUE THREAD

**Issue by sidristij** [sidristij/dotnetbook#57]
Здесь я предлагаю вести обсуждение главы. Ошибки, дополнения.

**Comment by sidristij** [comment]
Здесь я предлагаю вести обсуждение главы. Ошибки, дополнения.

**Comment by dinar007007** [comment]
В английской версии  перевод "Both subclasses can inherit the object type and become its representatives." звучит странно. Может "Both subclasses are inherited from object type ..." смотрится лучше?
