### ISSUE TITLE
Глава Стек потока

### ISSUE THREAD

**Issue by sidristij** [sidristij/dotnetbook#58]
Здесь я предлагаю вести обсуждение главы. Ошибки, дополнения.

**Comment by sidristij** [comment]
Здесь я предлагаю вести обсуждение главы. Ошибки, дополнения.

**Comment by DmitriyMaksimov** [comment]
Missing images on https://github.com/sidristij/dotnetbook/blob/master/book/ru/ThreadStack.md
Images location https://github.com/sidristij/dotnetbook/blob/master/book/ru/imgs/ThreadStack/step1.png, but actual location is https://github.com/sidristij/dotnetbook/blob/master/book//imgs/ (no /ru)

**Comment by sidristij** [comment]
Images pathes fixed

**Comment by alex-user** [comment]
Подскажите, а где код к главе?
Интересует вот эта строчка -` var forked = Fork.CloneThread();`

**Comment by doomviruz** [comment]
https://github.com/sidristij/dotnetex

**Comment by RomanDubinin** [comment]
Добрый день!
Возник вопрос о передаче параметров через регистры.

> Первое, что делает код, скомпилированный JIT'ом: он сохраняет параметры метода в стек (начиная с третьего). При этом первые два передаются через регистры. Тут важно помнить, что первым параметром экземплярных методов передаётся указатель на тот объект, с которым работает метод. Т.е. указатель this. Так что в этих (почти всех) случаях для регистров остаётся всего один параметр, а для всех остальных -- стек;

Что если первый параметр метода (второй после this) - структура, которая не помещается в регистр?
Ведь как мы знаем из главы `Ссылочные и значимые типы данных` параметр, принимающий значимый тип хранит в себе именно значение, а не ссылку.

**Comment by RomanDubinin** [comment]
Поторопился с вопросом)
Далее в главе `Ссылочные и значимые типы данных` написано о том, что каждое поле структуры - отдельный параметр метода. Вопрос решён)
